version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  piwik_data:
    driver: local
