version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - MARIADB_USER=bn_wordpress
      # - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami'
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MEDIAWIKI_DATABASE_USER=root
      - MEDIAWIKI_DATABASE_NAME=
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mariadb
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '81:80'
      - '1443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mediawiki
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '82:80'
      - '2443:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - wordpress
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  piwik_data:
    driver: local
  wordpress_data:
    driver: local