version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=127.0.0.1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASSWORD=your_password
  fluentd:
    image: 'smartkit/fluentd:latest'
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "phabricator"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"
    # networks:
    #  - front-tier
    #  - back-tier
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local