version: '2'
services:
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    container_name: mediawiki
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=root
      # - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '81:80'
      - '1443:443'
    volumes:
      - 'data_mediawiki:/bitnami'
volumes:
  data_mediawiki:
    driver: local
