version: '2'
services:
  piwik:
    image: 'bitnami/piwik:latest'
    container_name: piwik
    ports:
      - '82:80'
      - '2443:443'
    volumes:
      - 'piwik_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  piwik_data:
    driver: local
