version: '2'
services:
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '83:80'
      - '3443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=root
      # - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  wordpress_data:
    driver: local
