version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '$PWD/mariadb_data:/bitnami'
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$PWD/piwik_data:/bitnami'
    depends_on:
      - mariadb

# volumes:
#   mariadb_data:
#     driver: local
#   piwik_data:
#     driver: local
